/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:259097:
  appc.background(230);
} //_CODE_:window1:259097:

public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:strength:485376:
  println("custom_slider1 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:strength:485376:

public void custom_slider2_change1(GCustomSlider source, GEvent event) { //_CODE_:speed:799414:
  println("custom_slider2 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:speed:799414:

public void custom_slider3_change1(GCustomSlider source, GEvent event) { //_CODE_:agility:409325:
  println("custom_slider3 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:agility:409325:

public void custom_slider4_change1(GCustomSlider source, GEvent event) { //_CODE_:endurance:685171:
  println("endurance - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:endurance:685171:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 400, 300, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  label1 = new GLabel(window1, 17, 10, 101, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("GREEN TEAM");
  label1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  label1.setOpaque(false);
  strength = new GCustomSlider(window1, 17, 75, 100, 40, "grey_blue");
  strength.setShowValue(true);
  strength.setLimits(1, 1, 10);
  strength.setStickToTicks(true);
  strength.setShowTicks(true);
  strength.setNumberFormat(G4P.INTEGER, 0);
  strength.setOpaque(false);
  strength.addEventHandler(this, "custom_slider1_change1");
  speed = new GCustomSlider(window1, 17, 138, 100, 40, "grey_blue");
  speed.setShowValue(true);
  speed.setLimits(1, 1, 10);
  speed.setStickToTicks(true);
  speed.setShowTicks(true);
  speed.setNumberFormat(G4P.INTEGER, 0);
  speed.setOpaque(false);
  speed.addEventHandler(this, "custom_slider2_change1");
  agility = new GCustomSlider(window1, 14, 192, 100, 40, "grey_blue");
  agility.setShowValue(true);
  agility.setLimits(1, 1, 10);
  agility.setStickToTicks(true);
  agility.setShowTicks(true);
  agility.setNumberFormat(G4P.INTEGER, 0);
  agility.setOpaque(false);
  agility.addEventHandler(this, "custom_slider3_change1");
  endurance = new GCustomSlider(window1, 15, 230, 100, 40, "grey_blue");
  endurance.setShowValue(true);
  endurance.setLimits(1, 1, 10);
  endurance.setStickToTicks(true);
  endurance.setShowTicks(true);
  endurance.setNumberFormat(G4P.INTEGER, 0);
  endurance.setOpaque(false);
  endurance.addEventHandler(this, "custom_slider4_change1");
  label2 = new GLabel(window1, 27, 55, 80, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("My label");
  label2.setOpaque(false);
  label3 = new GLabel(window1, 27, 115, 80, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("My label");
  label3.setOpaque(false);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GLabel label1; 
GCustomSlider strength; 
GCustomSlider speed; 
GCustomSlider agility; 
GCustomSlider endurance; 
GLabel label2; 
GLabel label3; 
