/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:259097:
  appc.background(230);
} //_CODE_:window1:259097:

public void GreenStrength(GCustomSlider source, GEvent event) { //_CODE_:strengthT1:485376:
  st1 = strengthT1.getValueI();
} //_CODE_:strengthT1:485376:

public void GreenSpeed(GCustomSlider source, GEvent event) { //_CODE_:speedT1:799414:
  sp1 = speedT1.getValueI();
} //_CODE_:speedT1:799414:

public void GreenAgility(GCustomSlider source, GEvent event) { //_CODE_:agilityT1:409325:
  ag1 = agilityT1.getValueI();
} //_CODE_:agilityT1:409325:

public void GreenEndurance(GCustomSlider source, GEvent event) { //_CODE_:enduranceT1:685171:
  ed1 = enduranceT1.getValueI();
} //_CODE_:enduranceT1:685171:

public void RedStrength(GCustomSlider source, GEvent event) { //_CODE_:strengthT2:482780:
  st2 = strengthT2.getValueI();
} //_CODE_:strengthT2:482780:

public void RedSpeed(GCustomSlider source, GEvent event) { //_CODE_:speedT2:337312:
  sp2 = speedT2.getValueI();
} //_CODE_:speedT2:337312:

public void RedAgility(GCustomSlider source, GEvent event) { //_CODE_:agilityT2:228075:
  ag2 = agilityT2.getValueI();
} //_CODE_:agilityT2:228075:

public void RedEndurance(GCustomSlider source, GEvent event) { //_CODE_:enduranceT2:404878:
  ed2 = enduranceT2.getValueI();
} //_CODE_:enduranceT2:404878:

public void GreenTeamSize(GCustomSlider source, GEvent event) { //_CODE_:teamSize1:294389:
  teamSizeGreen = teamSize1.getValueI();
} //_CODE_:teamSize1:294389:

public void RedTeamSize(GCustomSlider source, GEvent event) { //_CODE_:teamSize2:247080:
  teamSizeRed = teamSize2.getValueI();
} //_CODE_:teamSize2:247080:

public void start_Stop(GButton source, GEvent event) { //_CODE_:startStop:598543:
  if( !start ) {
    start = true;
    people = new ArrayList<Person>();
    balls = new ArrayList<balloon>();
    createTeams();
    
  }
  else if( start ) {
    start = false;
    people = new ArrayList<Person>();
    balls = new ArrayList<balloon>();
  }
} //_CODE_:startStop:598543:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 400, 600, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  label1 = new GLabel(window1, 17, 10, 101, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("GREEN TEAM");
  label1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  label1.setOpaque(false);
  strengthT1 = new GCustomSlider(window1, 17, 55, 100, 56, "grey_blue");
  strengthT1.setShowValue(true);
  strengthT1.setLimits(1, 1, 10);
  strengthT1.setStickToTicks(true);
  strengthT1.setShowTicks(true);
  strengthT1.setNumberFormat(G4P.INTEGER, 0);
  strengthT1.setOpaque(false);
  strengthT1.addEventHandler(this, "GreenStrength");
  speedT1 = new GCustomSlider(window1, 15, 132, 100, 56, "grey_blue");
  speedT1.setShowValue(true);
  speedT1.setLimits(1, 1, 10);
  speedT1.setStickToTicks(true);
  speedT1.setShowTicks(true);
  speedT1.setNumberFormat(G4P.INTEGER, 0);
  speedT1.setOpaque(false);
  speedT1.addEventHandler(this, "GreenSpeed");
  agilityT1 = new GCustomSlider(window1, 13, 210, 100, 56, "grey_blue");
  agilityT1.setShowValue(true);
  agilityT1.setLimits(1, 1, 10);
  agilityT1.setStickToTicks(true);
  agilityT1.setShowTicks(true);
  agilityT1.setNumberFormat(G4P.INTEGER, 0);
  agilityT1.setOpaque(false);
  agilityT1.addEventHandler(this, "GreenAgility");
  enduranceT1 = new GCustomSlider(window1, 12, 293, 100, 56, "grey_blue");
  enduranceT1.setShowValue(true);
  enduranceT1.setLimits(1, 1, 10);
  enduranceT1.setStickToTicks(true);
  enduranceT1.setShowTicks(true);
  enduranceT1.setNumberFormat(G4P.INTEGER, 0);
  enduranceT1.setOpaque(false);
  enduranceT1.addEventHandler(this, "GreenEndurance");
  label3 = new GLabel(window1, 27, 117, 76, 13);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Speed");
  label3.setOpaque(false);
  label4 = new GLabel(window1, 22, 188, 80, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Agility");
  label4.setOpaque(false);
  label5 = new GLabel(window1, 21, 269, 80, 20);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Endurance");
  label5.setOpaque(false);
  label2 = new GLabel(window1, 27, 40, 80, 14);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Strength");
  label2.setOpaque(false);
  label6 = new GLabel(window1, 241, 117, 80, 20);
  label6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label6.setText("Speed");
  label6.setOpaque(false);
  label7 = new GLabel(window1, 241, 36, 80, 20);
  label7.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label7.setText("Strength");
  label7.setOpaque(false);
  label8 = new GLabel(window1, 230, 10, 101, 20);
  label8.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label8.setText("RED TEAM");
  label8.setLocalColorScheme(GCScheme.RED_SCHEME);
  label8.setOpaque(false);
  label9 = new GLabel(window1, 241, 188, 80, 20);
  label9.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label9.setText("Agility");
  label9.setOpaque(false);
  label10 = new GLabel(window1, 241, 269, 80, 20);
  label10.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label10.setText("Endurance");
  label10.setOpaque(false);
  strengthT2 = new GCustomSlider(window1, 229, 55, 100, 56, "grey_blue");
  strengthT2.setShowValue(true);
  strengthT2.setShowLimits(true);
  strengthT2.setLimits(1, 1, 10);
  strengthT2.setNumberFormat(G4P.INTEGER, 0);
  strengthT2.setOpaque(false);
  strengthT2.addEventHandler(this, "RedStrength");
  speedT2 = new GCustomSlider(window1, 229, 132, 100, 56, "grey_blue");
  speedT2.setShowValue(true);
  speedT2.setShowLimits(true);
  speedT2.setLimits(1, 1, 10);
  speedT2.setNumberFormat(G4P.INTEGER, 0);
  speedT2.setOpaque(false);
  speedT2.addEventHandler(this, "RedSpeed");
  agilityT2 = new GCustomSlider(window1, 229, 210, 100, 56, "grey_blue");
  agilityT2.setShowValue(true);
  agilityT2.setShowLimits(true);
  agilityT2.setLimits(1, 1, 10);
  agilityT2.setNumberFormat(G4P.INTEGER, 0);
  agilityT2.setOpaque(false);
  agilityT2.addEventHandler(this, "RedAgility");
  enduranceT2 = new GCustomSlider(window1, 229, 293, 100, 56, "grey_blue");
  enduranceT2.setShowValue(true);
  enduranceT2.setShowLimits(true);
  enduranceT2.setLimits(1, 1, 10);
  enduranceT2.setNumberFormat(G4P.INTEGER, 0);
  enduranceT2.setOpaque(false);
  enduranceT2.addEventHandler(this, "RedEndurance");
  label11 = new GLabel(window1, 8, 369, 109, 20);
  label11.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label11.setText("Green Team Size");
  label11.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  label11.setOpaque(false);
  teamSize1 = new GCustomSlider(window1, 12, 391, 100, 56, "grey_blue");
  teamSize1.setShowValue(true);
  teamSize1.setShowLimits(true);
  teamSize1.setLimits(1, 1, 4);
  teamSize1.setNumberFormat(G4P.INTEGER, 0);
  teamSize1.setOpaque(false);
  teamSize1.addEventHandler(this, "GreenTeamSize");
  label12 = new GLabel(window1, 230, 368, 101, 20);
  label12.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label12.setText("Red Team Size");
  label12.setLocalColorScheme(GCScheme.RED_SCHEME);
  label12.setOpaque(false);
  teamSize2 = new GCustomSlider(window1, 229, 391, 100, 56, "grey_blue");
  teamSize2.setShowValue(true);
  teamSize2.setShowLimits(true);
  teamSize2.setLimits(1, 1, 4);
  teamSize2.setNumberFormat(G4P.INTEGER, 0);
  teamSize2.setOpaque(false);
  teamSize2.addEventHandler(this, "RedTeamSize");
  startStop = new GButton(window1, 137, 12, 80, 30);
  startStop.setText("Start/Stop");
  startStop.addEventHandler(this, "start_Stop");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GLabel label1; 
GCustomSlider strengthT1; 
GCustomSlider speedT1; 
GCustomSlider agilityT1; 
GCustomSlider enduranceT1; 
GLabel label3; 
GLabel label4; 
GLabel label5; 
GLabel label2; 
GLabel label6; 
GLabel label7; 
GLabel label8; 
GLabel label9; 
GLabel label10; 
GCustomSlider strengthT2; 
GCustomSlider speedT2; 
GCustomSlider agilityT2; 
GCustomSlider enduranceT2; 
GLabel label11; 
GCustomSlider teamSize1; 
GLabel label12; 
GCustomSlider teamSize2; 
GButton startStop; 
